server:
  AppVersion: 1.0.0
  Port: :9191
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: true

mongodb:
  MongoURI: "mongodb+srv://twittor_user:TestUser123@twittor.blv2u.mongodb.net/myFirstDatabase"
